version: '3'

networks:
  patterns:
    driver: bridge

services:
  nginx:
    image: 'bitnami/nginx:latest'
    depends_on:
      - php-fpm
    networks:
      - patterns
    ports:
      - '80:8000'
      - '443:443'
    volumes:
      - ./docker/nginx.conf:/opt/bitnami/nginx/conf/server_blocks/app.conf
      - ./public/img:/app/public/img
    restart: unless-stopped
  
  php-fpm:
    image: 'bitnami/php-fpm:7.4'
    depends_on:
      - postgres
    networks:
      - patterns
    volumes:
      - ./:/app
    restart: unless-stopped
  
  postgres:
    image: postgres:11.7
    networks:
      - patterns
    build:
      dockerfile: docker/Dockerfile_pg
      context: .
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example